version: '3.10.6'
services:
  service-a:
    build: .
    command: python manage.py 
    ports:
      - "4000:4000"  
    restart: unless-stopped
    depends_on:
      - service-b

  service-b:
    build: .
    command: python chromadb_helper.py
    ports:
      - "5001:5001" 
    restart: unless-stopped